# Generated by Django 3.1 on 2022-06-27 03:02

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='date creation')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='date modification')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='date delete')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Category Product',
                'verbose_name_plural': 'Category Products',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='date creation')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='date modification')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='date delete')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Measure Unit',
                'verbose_name_plural': 'Measure Units',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='date creation')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='date modification')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='date delete')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='product image')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='date creation')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='date modification')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='date delete')),
                ('discount_value', models.PositiveBigIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Discount indicator')),
            ],
            options={
                'verbose_name': 'Offert Indicator',
                'verbose_name_plural': 'Offert Indicators',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='date creation')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='date modification')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='date delete')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='product image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='date creation')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='date modification')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='date delete')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical Measure Unit',
                'verbose_name_plural': 'historical Measure Units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='date creation')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='date modification')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='date delete')),
                ('discount_value', models.PositiveBigIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Discount indicator')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical Offert Indicator',
                'verbose_name_plural': 'historical Offert Indicators',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='date creation')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='date modification')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='date delete')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
            ],
            options={
                'verbose_name': 'historical Category Product',
                'verbose_name_plural': 'historical Category Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
